server.port: 8001
spring.datasource:
  url: jdbc:postgresql://localhost:5432/item_data
  username: item_data_admin
  password: xxxxxxxx

#Allow access to full health and metrics endpoints
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'